name: test Project
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v3

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
          
